baseURL = "https://www.samueladams.dev"
languageCode = "en-us"
title = "Samuel Adams"
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  description = "A place to (hopefully) learn interesting things about software."
  avatar = "avatar.jpg"
  author = "Samuel Adams"
  favicon = "/favicon.ico"

  [[params.social]]
    name = "github"
    url = "https://github.com/samueladamsonline"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/samueladamsonline/"

  [[params.social]]
    name = "twitch"
    url = "https://www.twitch.tv/phaedontv"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"