name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Hugo
        run: |
          sudo apt-get update
          sudo apt-get install hugo=0.68.3-1

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Generate HTML files
        run: hugo -d ../tmp/

      - name: Add CNAME file
        run: echo "www.samueladams.dev" >> CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ../tmp/

